# This is the Config File of FreeBungeeChat
# read readme.md for more information

# you can use %player%
chatFormat: '&b[%player%][/w %player% ] &f> %message%'

# you can use %target%
unknownTarget: '&c%target% is not on the server'

# you can use %player% and %target%
privateMessageSend: '&b[You -> %target%][/w %target% ]&f *> %message%'

# you can use %player% and %target%
privateMessageReceive: '&b[%player% -> me][/w %player% ] &f*> %message%'

# whether to treat all chat as global chat
# if this is set to false use /g for global chat
# IF YOU DON'T KNOW WHAT THIS DOES DON'T CHANGE IT
alwaysGlobalChat: true