# This is the Config File of FreeBungeeChat
# read readme.md for more information

# you can use %player%
chatFormat: '&b[%player%][/w %player% ] &f> %message%'

# you can use %target%
unknownTarget: '&c%target% is not on the server'

# you can use %target%, will be send when trying to message an player who ignores you
ignored: "&c%target% doesn't like you"

ignoreSuccess: '&7You ignored %target%'
ignoreUnignore: '&7You no longer ignore %target%'

# you can use %player% and %target%
privateMessageSend: '&b[You -> %target%][/w %target% ]&f *> %message%'

# you can use %player% and %target%
privateMessageReceive: '&b[%player% -> me][/w %player% ] &f*> %message%'

# whether to underline everything that is clickable or has a hover effect
underlineLinks: true

# you can add custom regular expressions here
regex:
# allows tagging players with @player
    - search: "@(?<name>[^ ]{1,16})"
      replace: "[@${name}][/w ${name}]"
# shows link target in tooltip for security reasons
    - search: '(?:(?<!\\)\[(?<text>[^\]]*?)(?<!\\)\](?=[({])(?:\((?<url>.*?)(?<!\\)\))(?:\{(?<tooltip>.*?)(?<!\\)\})?)'
      replace: "[${text}](${url}){${tooltip}%newline%${url}}"
# some smileys
    - search: '--->'
      replace: "\u21DB"
    - search: '<---'
      replace: "\u21DA"
    - search: '-->'
      replace: "\u21D2"
    - search: '<--'
      replace: "\u21D0"
    - search: '->'
      replace: "\u2192"
    - search: '<-'
      replace: "\u2190"
    - search: '(?i)\(C\)'
      replace: "\u00A9"
    - search: '(?i)\(R\)'
      replace: "\u00AE"
    - search: '\(o\)|\(O\)|\(time\)'
      replace: "\u231A"
    - search: '\(rain\)'
      replace: "\u2602"
    - search: '\(sun\)'
      replace: "\u2600"
    - search: '\(\*\)'
      replace: "\u2605"
    - search: ':\)|:=\)|:-\)'
      replace: "\u263A"
    - search: ':\(|:=\(|:-\('
      replace: "\u2639"
    - search: '(?i):[-=]?D'
      replace: "\u263B"
    - search: '<3'
      replace: "\u2764"

###########################################################
# ONLY EDIT BELOW SETTINGS IF YOU KNOW WHAT YOU ARE DOING #
###########################################################

# whether to treat all chat as global chat
# if this is set to false use /g for global chat
# IF YOU DON'T KNOW WHAT THIS DOES DON'T CHANGE IT
alwaysGlobalChat: true

# should be self-explaining
enableIgnoreCommand: true

# exclude servers from global chat, players on these servers will not be able to send or receive global chat
#excludeServers:
#  - spawn
#  - survival