# This is the Config File of FreeBungeeChat
# read readme.md for more information

# you can use %player%
chatFormat: '&b[%player%][/w %player% ] &f> %message%'

# you can use %target%
unknownTarget: '&c%target% is not on the server'

# you can use %target%, will be send when trying to message an player who ignores you
ignored: "&c%target% doesn't like you"

ignoreSuccess: '&7You ignored %target%'
ignoreUnignore: '&7You no longer ignore %target%'

# you can use %player% and %target%
privateMessageSend: '&b[You -> %target%][/w %target% ]&f *> %message%'

# you can use %player% and %target%
privateMessageReceive: '&b[%player% -> me][/w %player% ] &f*> %message%'

# whether to underline everything that is clickable or has a hover effect
underlineLinks: true

# you can add custom regular expressions here
regex:
# allows tagging players with @player
    - search: "@(?<name>.{1,16})"
      replace: "[@${name}][/w ${name}]"
# shows link target in tooltip for security reasons
    - search: '(?:(?<!\\)\[(?<text>[^\]]*?)(?<!\\)\](?=[({])(?:\((?<url>.*?)(?<!\\)\))(?:\{(?<tooltip>.*?)(?<!\\)\})?)'
      replace: "[${text}](${url}){${tooltip}%newline%${url}}"

###########################################################
# ONLY EDIT BELOW SETTINGS IF YOU KNOW WHAT YOU ARE DOING #
###########################################################

# whether to treat all chat as global chat
# if this is set to false use /g for global chat
# IF YOU DON'T KNOW WHAT THIS DOES DON'T CHANGE IT
alwaysGlobalChat: true

# should be self-explaining
enableIgnoreCommand: true

# exclude servers from global chat, players on these servers will not be able to send or receive global chat
#excludeServers:
#  - spawn
#  - survival